//
// Created by m on 24.11.2023.
//

#ifndef ROYAL_TRACER_KERNELCONSTANTS_H
#define ROYAL_TRACER_KERNELCONSTANTS_H

#define EPSILON 3e-6f
#define MIN_WAVELENGTH 380.0f
#define MAX_WAVELENGTH 780.0f
#define FOGINTENSITY 0.0f
#define FOGDISTANCE 0.0f


#endif //ROYAL_TRACER_KERNELCONSTANTS_H
